name: heheheha

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Trolling:
    name: trolling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: troll
        run: echo heheheha
